title: <p align="center">Debabrato Sengupta</p>
logo: /assets/img/BB3981pp.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/debabrato-sengupta-b3a207144/">LinkedIn</a> |
  <a href="https://github.com/debabrato">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Tech Mahindra Ltd.
  <br>
  </p>
